-- DROP DATABASE GROCERY_STORE;

CREATE DATABASE GROCERY_STORE;

USE GROCERY_STORE;
 
-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);




-- Analysis Questions

-- Customer Insights

-- How many unique customers have placed orders?

SELECT COUNT(DISTINCT CUST_ID) AS unique_customers
FROM ORDERS;


-- Which customers have placed the highest number of orders?

SELECT cust_id,cust_name,order_count
FROM (
    SELECT c.cust_id,
           c.cust_name,
           COUNT(*) AS order_count,
           DENSE_RANK() OVER (
               ORDER BY COUNT(*) DESC
           ) AS rnk
    FROM customers c
    JOIN orders o
        ON c.cust_id = o.cust_id
    GROUP BY c.cust_id, c.cust_name
) t
WHERE rnk = 1;



-- What is the total and average purchase value per customer?

SELECT o.cust_id,
       SUM(od.total_price) AS total_purchase,
       AVG(od.total_price) AS avg_purchase
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
GROUP BY o.cust_id;

-- Who are the top 5 customers by total purchase amount?

SELECT o.cust_id,c.cust_name,
       SUM(od.total_price) AS total_purchase
FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id
join customers c 
on c.cust_id=o.cust_id
GROUP BY o.cust_id
order by total_purchase desc
limit 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.


-- How many products exist in each category?

select c.cat_name ,count(*) no_of_products
from products p
join categories c
on p.cat_id = c.cat_id
group by p.cat_id;


-- What is the average price of products by category?

SELECT cat_id,
       AVG(price) AS avg_price
FROM products
GROUP BY cat_id;


-- Which products have the highest total sales volume (by quantity)?

SELECT p.prod_id,p.prod_name,t.total
FROM (
    SELECT prod_id,
           SUM(quantity) AS total,
           DENSE_RANK() OVER (
               ORDER BY SUM(quantity) DESC
           ) AS rnk
    FROM order_details
    GROUP BY prod_id
) t
JOIN products p
ON p.prod_id = t.prod_id
WHERE rnk = 1;

-- What is the total revenue generated by each product?

select prod_id, sum(total_price) total_revenue
from order_details
group by prod_id;

-- How do product sales vary by category and supplier?

select c.cat_name , s.sup_name ,sum(o.total_price) total_sales
from order_details o
join products p
	on p.prod_id = o.prod_id
join  categories c
	on c.cat_id = p.cat_id
join supplier s
	on s.sup_id = p.sup_id
group by c.cat_id,s.sup_id
order by total_sales desc;



-- 3. Sales and Order Trends
-- How many orders have been placed in total?
select count(distinct ord_id) total_orders
from orders;


-- What is the average value per order?

SELECT AVG(order_value) AS avg_order_value
FROM (
    SELECT ord_id,
           SUM(total_price) AS order_value
    FROM order_details
    GROUP BY ord_id
) t;



-- On which dates were the most orders placed?

SELECT order_date,
       total_orders
FROM (
    SELECT order_date,
           COUNT(*) AS total_orders,
           DENSE_RANK() OVER (
               ORDER BY COUNT(*) DESC
           ) AS rnk
    FROM orders
    GROUP BY order_date
) t
WHERE rnk = 1;


-- What are the monthly trends in order volume and revenue?

SELECT 
    DATE_FORMAT(STR_TO_DATE(o.order_date, '%m/%d/%Y'), '%Y-%m') AS order_month,
    COUNT(DISTINCT o.ord_id) AS order_volume,
    SUM(od.total_price) AS revenue
FROM orders o
JOIN order_details od
    ON o.ord_id = od.ord_id
GROUP BY 
    DATE_FORMAT(STR_TO_DATE(o.order_date, '%m/%d/%Y'), '%Y-%m')
ORDER BY 
    order_month;


-- How do order patterns vary across weekdays and weekends?
SELECT
CASE
WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%m/%d/%Y')) IN (1, 7)
THEN 'Weekend'
ELSE 'Weekday'
END AS day_type,

COUNT(DISTINCT o.ord_id) AS total_orders,
SUM(od.total_price) AS total_revenue

FROM orders o
JOIN order_details od
ON o.ord_id = od.ord_id

GROUP BY
CASE
WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%m/%d/%Y')) IN (1, 7)
THEN 'Weekend'
ELSE 'Weekday'
END;


-- 4️. Supplier Contribution

-- How many suppliers are there in the database?
select count(*) as total_suppliers
from supplier;

-- Which supplier provides the most products?

SELECT t.sup_id,s.sup_name,
       products
FROM (
    SELECT sup_id,
           COUNT(*) AS products,
           DENSE_RANK() OVER (
               ORDER BY COUNT(*) DESC
           ) AS rnk
    FROM products
    GROUP BY sup_id
) t
join supplier s 
on s.sup_id=t.sup_id
WHERE rnk = 1;

-- What is the average price of products from each supplier?
select sup_id,avg(price) avge
from products
group by sup_id;


-- Which suppliers contribute the most to total product sales (by revenue)?

SELECT t.sup_id,s.sup_name,
       revenue
FROM (
    SELECT p.sup_id,
           SUM(od.total_price) AS revenue,
           DENSE_RANK() OVER (
               ORDER BY SUM(od.total_price) DESC
           ) AS rnk
    FROM products p
    JOIN order_details od
        ON p.prod_id = od.prod_id
    GROUP BY p.sup_id
) t
join supplier s 
on s.sup_id=t.sup_id
WHERE rnk = 1;


-- 5️. Employee Performance
-- How many employees have processed orders?

select count(distinct emp_id)
from orders;

-- Which employees have handled the most orders?

select emp_id,orders
from (
select emp_id,orders,dense_rank() over (
					order by orders desc
                    ) as rnk
from (select emp_id,count(*) orders
		from orders
		group by emp_id
        ) x
        ) y
        where rnk =1;


-- What is the total sales value processed by each employee?

SELECT o.emp_id,
       SUM(od.total_price) AS total_sales
FROM orders o
JOIN order_details od
    ON o.ord_id = od.ord_id
GROUP BY o.emp_id
ORDER BY o.emp_id;


-- What is the average order value handled per employee?

SELECT p.emp_id,
       AVG(o.total) AS avg_order_value
FROM (
    SELECT ord_id,
           SUM(total_price) AS total
    FROM order_details
    GROUP BY ord_id
) o
JOIN orders p
    ON p.ord_id = o.ord_id
GROUP BY p.emp_id
ORDER BY p.emp_id;


-- 6️. Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?

SELECT quantity,
       AVG(total_price) AS avg_total_price,
       COUNT(*) AS orders
FROM order_details
GROUP BY quantity
ORDER BY quantity;


-- What is the average quantity ordered per product?

SELECT p.prod_name,
       AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od
    ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY p.prod_id;


-- How does the unit price vary across products and orders?

SELECT p.prod_name,
       MIN(od.each_price) AS min_price,
       MAX(od.each_price) AS max_price,
       AVG(od.each_price) AS avg_price
FROM products p
JOIN order_details od
    ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY p.prod_id;


SELECT * FROM products;
SELECT * FROM supplier;
SELECT * FROM order_details; 
SELECT * FROM orders;
SELECT * FROM customers;
SELECT * FROM employees;
SELECT * FROM categories;